- hosts: localhost
  tasks:
      - name: Add syncthing key
        become: yes
        apt_key:
            url: https://syncthing.net/release-key.txt
            state: present
      - name: Add syncthing repo
        become: yes
        apt_repository:
            repo: deb https://apt.syncthing.net/ syncthing stable
            state: present
      - name: Install packages
        become: yes
        package:
                name: "{{item}}"
                state: latest
        with_items:
                - syncthing
      - name: Enable Syncthing
        become: yes
        systemd:
            state: started
            enabled: yes
            name: "syncthing@{{ ansible_user}}"
