
- hosts: localhost
  tasks:
      - name: Add Apt keys
        become: yes
        apt_key:
            url: "{{ item }}"
            state: present
        loop:
            - https://download.docker.com/linux/{{ ansible_lsb.id|lower }}/gpg
      - name: Add PPAs
        become: yes
        apt_repository:
                repo: "{{item}}"
                state: present
        loop:
#            - ppa:fish-shell/release-3
            - ppa:neovim-ppa/stable
              #- "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
            - "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_lsb.id|lower }} {{ ansible_lsb.codename }} stable test"
      - name: Install packages
        become: yes
        package:
            name: "{{item}}"
            state: latest
        loop:
            - git
            - mercurial
            - neovim
            - fish
              #            - firefox
            - tilix
            - tmux
            - htop
            - exfat-fuse
            - exfat-utils
            - flatpak
            - gnome-software-plugin-flatpak
            - firmware-atheros
            - rsync
            - autossh

            - python-dev
            - python3-dev
            - python3-venv
            - python-psutil
            - python3-psutil
            - python3-pip
            - python-distutils-extra
            - python3-distutils-extra

            - silversearcher-ag
            - ranger
            - gnome-tweak-tool

            - docker-ce
            - docker-ce-cli
            - containerd.io
      - name: Install pip packages
        become: yes
        pip:
            executable: pip3
            state: latest
            name:
                - virtualfish
                - pipx
      - name: Install Pipx packages
        command: pipx install "{{ item }}"
        loop:
            - docker-compose
            - gnome-shell-install-extension
            - xkcdpass
      - name: Install the flathub repository
        become: yes
        flatpak_remote:
            name: flathub 
            flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
            state: present
      - name: Install Flatpak apps
        become: yes
        flatpak:
            name: "{{ item }}"
            state: present
        loop:
            - org.gimp.GIMP
            - com.slack.Slack
      - name: Remove packages
        become: yes
        package:
            name: "{{item}}"
            state: absent
        loop:
            - thunderbird
            - vim
      - name: create directory for Firefox
        become: yes
        file:
            path: /opt/firefox
            state: directory
      - name: Get Firefox
        become: yes
        unarchive:
            src: https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-GB
            remote_src: true
            dest: /opt/firefox
            creates: /opt/firefox/firefox
      - name: Add Firefox to applications
        become: yes
        copy:
            src: firefox-stable.desktop
            dest: /usr/share/applications/firefox.desktop
      - name: Set user shell + groups
        become: yes
        user:
            name: "{{ ansible_user }}"
            groups: adm,docker
            append: yes
            shell: /usr/bin/fish
      - name: Reduce swappiness
        become: yes
        sysctl:
            name: vm.swappiness
            value: 2
      - name: Reduce VFS cache pressure
        become: yes
        sysctl:
            name: vm.vfs_cache_pressure
            value: 50
      - name: Find the latest release
        uri:
            url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
            return_content: true
        register: nerd_font_release
      - name: Download Sauce Code Pro
        unarchive:
            dest: ~/.local/share/fonts/
            remote_src: true
            src: "{{ item.browser_download_url }}"
        loop: "{{ nerd_font_release.json.assets }}"
        when: item["name"] == "SourceCodePro.zip"
      - name: create directory for Gnome shell extensions
        file:
            path: /tmp/gnome-shell-extensions
            state: directory
      - name: download Gnome shell extensions
        get_url:
            url: https://extensions.gnome.org/extension-data/{{ item }}
            dest: /tmp/gnome-shell-extensions/
        loop:
            - Move_Clockrmy.pobox.com.v19.shell-extension.zip
            - drive-menu@gnome-shell-extensions.gcampax.github.com.v38.shell-extension.zip
            - dash-to-dockmicxgx.gmail.com.v65.shell-extension.zip
      - name: Install Gnome shell extensions
        command: ~/.local/bin/gnome-shell-install-extension {{ item }}
        with_fileglob:
            - /tmp/gnome-shell-extensions/*.zip
      - name: Change dconf settings
        dconf:
            key: "{{ item.key }}"
            value: "{{ item.value }}"
        loop:
            - { key: /org/gnome/settings-daemon/plugins/color/night-light-enabled, value: 'true' }
            - { key: /org/gnome/settings-daemon/plugins/color/night-light-temperature, value: uint32 3500 }
              #
            # free the <Super+`> keybinding
            - { key: /org/gnome/desktop/wm/keybindings/switch-group, value:  '@as []' }
            - { key: /org/gnome/desktop/wm/keybindings/switch-group-backward, value:  '@as []' }
            # hide the dock
            - { key: /org/gnome/shell/extensions/dash-to-dock/autohide, value: 'false' }
            - { key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed, value: 'false' }
            - { key: /org/gnome/shell/extensions/dash-to-dock/intellihide, value: 'false' }

            - { key: /org/gnome/desktop/interface/clock-show-seconds, value: 'true' }
            - { key: /org/gnome/desktop/interface/monospace-font-name, value: '"SauceCodePro Nerd Font 16"' }
            - { key: /org/gnome/shell/favorite-apps, value: "['com.slack.Slack.desktop', 'firefox.desktop', 'com.gexperts.Tilix.desktop']" }

            - { key: /org/gnome/shell/extensions/desktop-icons/show-trash, value: 'false' }
            - { key: /org/gnome/shell/extensions/desktop-icons/show-home, value: 'false' }

            # Tilix settings
            - { key: /com/gexperts/Tilix/terminal-title-show-when-single, value: 'true' }
            - { key: /com/gexperts/Tilix/theme-variant, value: '"dark"' }
            - { key: /com/gexperts/Tilix/quake-specific-monitor, value: 0 }
            - { key: /com/gexperts/Tilix/terminal-title-style, value: '"none"' }
            - { key: /com/gexperts/Tilix/window-style, value: '"borderless"' }
            - { key: /com/gexperts/Tilix/use-overlay-scrollbar, value: 'true' }
            - { key: /com/gexperts/Tilix/keybindings/session-switch-to-terminal-right, value: '"disabled"' }
            - { key: /com/gexperts/Tilix/keybindings/session-switch-to-terminal-left, value: '"disabled"' }

            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/foreground-color, value: '"#EFEFEF"' }
            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/use-system-font, value: 'true' }
            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/badge-color, value: '"#AC7EA8"' }
            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/badge-color-set, value: 'true' }
            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/cursor-colors-set, value: 'false' }
            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/bold-color-set, value: 'false' }
            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/background-transparency-percent, value: 10 }
            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/background-color, value: '"#000000000000"' }
            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/highlight-colors-set, value: 'false' }
            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/use-theme-colors, value: 'false' }
            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/visible-name, value: '"dark"' }
            - { key: /com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/palette, value: "['#000000', '#CC0000', '#4D9A05', '#C3A000', '#3464A3', '#754F7B', '#05979A', '#D3D6CF', '#545652', '#EF2828', '#89E234', '#FBE84F', '#729ECF', '#AC7EA8', '#34E2E2', '#EDEDEB']" }
