- hosts: localhost
  tasks:
      - name: Add Ansible PPA
        become: yes
        apt_repository:
            repo: ppa:ansible/ansible
            state: present
      - name: Install Ansible
        become: yes
        package: 
            name: ansible
            state: latest
      - name: Add Apt keys
        become: yes
        apt_key:
            url: "{{ item }}"
            state: present
        loop:
            - https://download.docker.com/linux/ubuntu/gpg
      - name: Add PPAs
        become: yes
        apt_repository:
                repo: "{{item}}"
                state: present
        loop:
                - ppa:fish-shell/release-3
                - ppa:neovim-ppa/stable
                #- "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
                - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable test"
      - name: Install packages
        become: yes
        package:
                name: "{{item}}"
                state: latest
        loop:
                - git
                - mercurial
                - neovim
                - fish
                - firefox
                - tilix
                - python-psutil
                - python3-psutil
                - silversearcher-ag
                - ranger
                - gnome-tweak-tool
                
                - docker-ce
                - docker-ce-cli
                - containerd.io

      - name: Install Pipx packages
        command: pipx install "{{ item }}"
        loop:
            - docker-compose
      - name: Install snap packages
        snap:
            name: slack
            state: present
      - name: Remove packages
        become: yes
        package:
                name: "{{item}}"
                state: absent
        loop:
                - thunderbird
                - vim
      - name: Set user shell + groups
        become: yes
        user:
            name: "{{ ansible_user }}"
            groups: adm,docker
            append: yes
            shell: /usr/bin/fish
      - name: Get Nerd Fonts
        git:
            repo: 'https://github.com/ryanoasis/nerd-fonts'
            dest: /tmp/fonts
            depth: 1
            recursive: no
      - name: Install Source Code Pro
        command: ./install.sh SourceCodePro
        args:
            chdir: /tmp/fonts
            #creates: '~/.local/share/fonts/Source Code Pro for Powerline.otf'
      - name: Change dconf settings
        dconf:
            key: "{{ item.key }}"
            value: "{{ item.value }}"
        loop:
            - { key: /org/gnome/settings-daemon/plugins/color/night-light-enabled, value: 'true' }
            - { key: /org/gnome/settings-daemon/plugins/color/night-light-temperature, value: uint32 3500 }
              #
            # free the <Super+`> keybinding
            - { key: /org/gnome/desktop/wm/keybindings/switch-group, value:  '@as []' }
            - { key: /org/gnome/desktop/wm/keybindings/switch-group-backward, value:  '@as []' }
            # hide the dock
            - { key: /org/gnome/shell/extensions/dash-to-dock/autohide, value: 'false' }
            - { key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed, value: 'false' }
            - { key: /org/gnome/shell/extensions/dash-to-dock/intellihide, value: 'false' }

            - { key: /org/gnome/desktop/interface/clock-show-seconds, value: 'true' }
            - { key: /org/gnome/desktop/interface/monospace-font-name, value: '"SauceCodePro Nerd Font 16"' }
            - { key: /org/gnome/shell/favorite-apps, value: "['slack_slack.desktop', 'firefox.desktop', 'com.gexperts.Tilix.desktop']" }

