- hosts: localhost
  tasks:
      - name: Add Ansible PPA
        become: yes
        apt_repository:
            repo: ppa:ansible/ansible
            state: present
      - name: Install Ansible
        become: yes
        package: 
            name: ansible
            state: latest
      - name: Add PPAs
        become: yes
        apt_repository:
                repo: "{{item}}"
                state: present
        with_items:
                - ppa:fish-shell/release-3
                - ppa:neovim-ppa/stable
      - name: Install packages
        become: yes
        package:
                name: "{{item}}"
                state: latest
        with_items:
                - git
                - mercurial
                - neovim
                - fish
                - firefox
                - tilix
                - python-psutil
                - python3-psutil
                - silversearcher-ag
                - ranger
                - gnome-tweak-tool
      - name: Remove packages
        become: yes
        package:
                name: "{{item}}"
                state: absent
        with_items:
                - thunderbird
                - vim
      - name: Get Powerline fonts
        git:
            repo: 'https://github.com/powerline/fonts.git'
            dest: /tmp/fonts
            depth: 1
      - name: Install Powerline fonts
        command: ./install.sh
        args:
            chdir: /tmp/fonts
            creates: '~/.local/share/fonts/Source Code Pro for Powerline.otf'
      - name: Change dconf settings
        dconf:
            key: "{{ item.value.key }}"
            value: "{{ item.value.value }}"
        with_dict:
            enable_night_light:
                key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
                value: 'true'
            set_night_light_temperature:
                key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
                value: uint32 3500
            # free the <Super+`> keybinding
            disable_switch_group:
                key: /org/gnome/desktop/wm/keybindings/switch-group
                value:  '@as []'
            disable_switch_group_backward:
                key: /org/gnome/desktop/wm/keybindings/switch-group-backward
                value:  '@as []'
            # hide the dock
            dock_autohide:
                key: /org/gnome/shell/extensions/dash-to-dock/autohide
                value: 'false'
            dock_fixed:
                key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed
                value: 'false'
            intellihide:
                key: /org/gnome/shell/extensions/dash-to-dock/intellihide
                value: 'false'
            show_seconds:
                key: /org/gnome/desktop/interface/clock-show-seconds
                value: 'true'
            set_monospace_font:
                key: /org/gnome/desktop/interface/monospace-font-name
                value: '"Source Code Pro for Powerline Medium 16"'
            set_dock_favourites:
                key: /org/gnome/shell/favorite-apps
                value: "['firefox.desktop', 'com.gexperts.Tilix.desktop']"

