- hosts: localhost
  tasks:
      - name: Add Apt keys
        become: yes
        apt_key:
            url: "{{ item }}"
            state: present
        loop:
            - https://download.docker.com/linux/ubuntu/gpg
      - name: Add PPAs
        become: yes
        apt_repository:
                repo: "{{item}}"
                state: present
        loop:
            - ppa:fish-shell/release-3
            - ppa:neovim-ppa/stable
              #- "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
            - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable test"
      - name: Install packages
        become: yes
        package:
            name: "{{item}}"
            state: latest
        loop:
            - git
            - mercurial
            - neovim
            - fish
            - firefox
            - tilix
            - tmux
            - htop
            - exfat-fuse
            - exfat-utils
            - flatpak
            - gnome-software-plugin-flatpak

            - python-dev
            - python3-dev
            - python3-venv
            - python-psutil
            - python3-psutil
            - python3-pip
            - python-distutils-extra
            - python3-distutils-extra

            - silversearcher-ag
            - ranger
            - gnome-tweak-tool

            - docker-ce
            - docker-ce-cli
            - containerd.io
      - name: Install pip packages
        become: yes
        pip:
            executable: pip3
            state: latest
            name:
                - virtualfish
                - pipx
      - name: Install Pipx packages
        command: pipx install "{{ item }}"
        loop:
            - docker-compose
            - gnome-shell-install-extension
      - name: Install the flathub repository
        become: yes
        flatpak_remote:
            name: flathub 
            flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
            state: present
      - name: Install Flatpak apps
        become: yes
        flatpak:
            name: "{{ item }}"
            state: present
        loop:
            - org.gimp.GIMP
            - com.slack.Slack
      - name: Remove packages
        become: yes
        package:
            name: "{{item}}"
            state: absent
        loop:
            - thunderbird
            - vim
      - name: Set user shell + groups
        become: yes
        user:
            name: "{{ ansible_user }}"
            groups: adm,docker
            append: yes
            shell: /usr/bin/fish
      - name: Get Nerd Fonts
        git:
            repo: 'https://github.com/ryanoasis/nerd-fonts'
            dest: /tmp/fonts
            depth: 1
            recursive: no
      - name: Install Source Code Pro
        command: ./install.sh SourceCodePro
        args:
            chdir: /tmp/fonts
            #creates: '~/.local/share/fonts/Source Code Pro for Powerline.otf'
      - name: create directory for Gnome shell extensions
        file:
            path: /tmp/gnome-shell-extensions
            state: directory
      - name: download Gnome shell extensions
        get_url:
            url: https://extensions.gnome.org/extension-data/{{ item }}
            dest: /tmp/gnome-shell-extensions/
        loop:
            - Move_Clockrmy.pobox.com.v19.shell-extension.zip
            - drive-menugnome-shell-extensions.gcampax.github.com.v40.shell-extension.zip
      - name: Install Gnome shell extensions
        command: gnome-shell-install-extension /tmp/gnome-shell-extensions/*.zip
      - name: Change dconf settings
        dconf:
            key: "{{ item.key }}"
            value: "{{ item.value }}"
        loop:
            - { key: /org/gnome/settings-daemon/plugins/color/night-light-enabled, value: 'true' }
            - { key: /org/gnome/settings-daemon/plugins/color/night-light-temperature, value: uint32 3500 }
              #
            # free the <Super+`> keybinding
            - { key: /org/gnome/desktop/wm/keybindings/switch-group, value:  '@as []' }
            - { key: /org/gnome/desktop/wm/keybindings/switch-group-backward, value:  '@as []' }
            # hide the dock
            - { key: /org/gnome/shell/extensions/dash-to-dock/autohide, value: 'false' }
            - { key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed, value: 'false' }
            - { key: /org/gnome/shell/extensions/dash-to-dock/intellihide, value: 'false' }

            - { key: /org/gnome/desktop/interface/clock-show-seconds, value: 'true' }
            - { key: /org/gnome/desktop/interface/monospace-font-name, value: '"SauceCodePro Nerd Font 16"' }
            - { key: /org/gnome/shell/favorite-apps, value: "['com.slack.Slack.desktop', 'firefox.desktop', 'com.gexperts.Tilix.desktop']" }

            - { key: org/gnome/shell/extensions/desktop-icons/show-trash, value: 'false' }
            - { key: org/gnome/shell/extensions/desktop-icons/show-home, value: 'false' }

