- hosts: localhost
  vars:
      - op_version: 0.5.7
  tasks:
      - name: Add Apt keys
        become: yes
        apt_key:
            url: "{{ item }}"
            state: present
        loop:
            - https://packages.microsoft.com/keys/microsoft.asc
            - https://packages.cloud.google.com/apt/doc/apt-key.gpg
            - https://deb.goaccess.io/gnugpg.key
      - name: Add PPAs
        become: yes
        apt_repository:
                repo: "{{item}}"
                state: present
        loop:
                - "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ansible_lsb.codename}} main"
                - "deb http://deb.goaccess.io/ bionic main"
                #- "deb http://deb.goaccess.io/ {{ansible_lsb.codename}} main"
                - deb https://apt.kubernetes.io/ kubernetes-xenial main
      - name: Install packages
        become: yes
        package:
                name: "{{item}}"
                state: latest
        loop:
                - azure-cli
                - kubectl
                - golang
                - amazon-ecr-credential-helper
                - goaccess
                - virt-manager
      - name: Install snap packages
        snap:
            name:
                - heroku
                - helm
            state: present
      - name: Get Kubectx/Kubens
        become: yes
        git:
            repo: 'https://github.com/ahmetb/kubectx'
            dest: /opt/kubectx
            depth: 1
      - name: Ensure paths exist
        file:
            name: "{{ item }}"
            state: directory
        loop:
            - ~/.local/bin
            - ~/.config/fish/completions
      - name: Setup symlinks
        file:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            state: link
        loop:
            - { src: /opt/kubectx/kubectx, dest: ~/.local/bin/kubectx }
            - { src: /opt/kubectx/kubens, dest: ~/.local/bin/kubens }
            - { src: /opt/kubectx/completion/kubectx.fish, dest: ~/.config/fish/completions/kubectx.fish }
            - { src: /opt/kubectx/completion/kubens.fish, dest: ~/.config/fish/completions/kubens.fish }
      - name: Install Go packages
        command: go get -u "{{ item }}"
        loop:
            - github.com/wallix/awless
            - github.com/tsenart/vegeta
            - github.com/aykamko/tag
      - name: Install Pipx packages
        command: pipx install "{{ item }}"
        loop:
            - awscli
            - httpie
            - saws
      - name: Install 1password
        unarchive:
            src: https://cache.agilebits.com/dist/1P/op/pkg/v{{ op_version }}/op_linux_amd64_v{{ op_version }}.zip
            dest: ~/.local/bin
            remote_src: yes
